version: "3"
services:
#  portfolio-tracker:
#    image: portfolio-tracker
#    ports:
#      - "8080:8080"
#    networks:
#      - portfolio-tracker-mysql
#    depends_on:
#      - mysqldb

  mysqldb:
    image: mysql:8
    ports:
      - "3305:3306"
    networks:
      - portfolio-tracker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=portfolio-tracker-db

networks:
  portfolio-tracker-mysql: